---
- name: add ansible ppa
  apt_repository:
    repo: 'ppa:ansible/ansible'
    codename: trusty
    filename: ansible
    state: present
    # validate_certs: no

- name: update cache
  shell: apt-get update

- name: install ansible
  apt: name=ansible state=latest
